# Adapted from the "simple" Travis configuration at
#   https://docs.haskellstack.org/en/stable/travis_ci/
# but this version runs both stack and cabal.

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal
  - dist-newstyle
  - .stack-work

# Ensure necessary system libraries are present
#addons:
  #apt:
    #packages:
      # this installs the system version of ghc; we install ghc using stack instead
      #- libgmp-dev
      #- ghc
      # this installs an older version of cabal which doesn't support new-build
      #- cabal-install

env:
- BUILD=stack STACK_YAML="oldest-supported-lts.yaml"

- BUILD=stack STACK_YAML="stack.yaml"
- BUILD=cabal STACK_YAML="stack.yaml"
- BUILD=error-messages STACK_YAML="stack.yaml"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
# Install a recent version of cabal which supports new-build
- stack install cabal-install
# Make sure stack and cabal use the same ghc version
- export PATH="$(stack --stack-yaml="$STACK_YAML" path --compiler-bin):$PATH"

install:
# Build the package, and its tests and its docs (stack)
- if [ "$BUILD" == "stack" ]; then stack --stack-yaml="$STACK_YAML" --no-terminal --install-ghc test --no-run-tests --haddock --no-haddock-deps; fi
# Build the package and its tests (cabal)
- if [ "$BUILD" == "cabal" ]; then ~/.local/bin/cabal v2-update; fi
- if [ "$BUILD" == "cabal" ]; then ~/.local/bin/cabal v2-build --enable-tests; fi

script:
# Run the tests (stack)
- if [ "$BUILD" == "stack" ]; then stack --stack-yaml="$STACK_YAML" --no-terminal test; fi
# Run the tests (cabal)
- if [ "$BUILD" == "cabal" ]; then ~/.local/bin/cabal v2-test; fi
# Run the tests (error-messages)
- if [ "$BUILD" == "error-messages" ]; then ./test/error-messages/Test.hs; fi
