name:                typelevel-rewrite-rules
version:             0.1
synopsis:            Solve type equalities using custom type-level rewrite rules
#description:         
homepage:            https://github.com/gelisam/typelevel-rewrite-rules#readme
github:              gelisam/typelevel-rewrite-rules
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Type System
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.12
  - ghc-prim >= 0.5.3

library:
  source-dirs:      src
  ghc-options: -W -Wall
  dependencies:
    - ghc >= 8.6.3
    - ghc-tcplugins-extra >= 0.3
    - term-rewriting >= 0.3.0.1
    - transformers >= 0.5.5.0

tests:
  should-compile:
    source-dirs: test/should-compile
    main: Test.hs
    dependencies:
      - typelevel-rewrite-rules
      - vinyl
