name:                typelevel-rewrite-rules
version:             0.1.0.0
#synopsis:            
#description:         
homepage:            https://github.com/gelisam/typelevel-rewrite-rules#readme
github:              gelisam/typelevel-rewrite-rules
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Type System
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - ghc-prim

library:
  source-dirs:      src
  ghc-options: -W -Wall
  dependencies:
    - ghc
    - ghc-tcplugins-extra
    - transformers

tests:
  check-if-it-compiles:
    source-dirs: test
    main: Test.hs
    dependencies:
      - typelevel-rewrite-rules
      - vinyl
